name: Build_and_Release_Packages

on:
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cx_Freeze 

    - name: Build packages
      run: |
        python setup.py bdist_msi
        python setup.py bdist_mac
        python setup.py bdist_deb
        python setup.py bdist_rpm
        ls dist

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./artifacts

    - name: Upload MSI to Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/MSI/*.msi
      if: steps.download.outputs.found

    - name: Upload APP to Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/APP/*.app
      if: steps.download.outputs.found

    - name: Upload DEB to Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/DEB/*.deb
      if: steps.download.outputs.found

    - name: Upload RPM to Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/RPM/*.rpm
      if: steps.download.outputs.found
