name: Build_and_Release_Packages

on:
  release:
    types: [published]
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: './requirements.txt'

    - name: Build dependencies and packages
      run: |
        python -m pip install --upgrade pip
        pip install cx_Freeze 
        pip install -r requirements.txt
        touch variables.env
        ls .
        python setup.py build
        ls ./dist
        ls ./build

    - name: Validate dist folder
      run: ls ./dist && ls ./build

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./artifacts

    - name: Upload MSI to Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/MSI/*.msi
      if: steps.download.outputs.found

    - name: Upload APP to Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/APP/*.app
      if: steps.download.outputs.found

    - name: Upload DEB to Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/DEB/*.deb
      if: steps.download.outputs.found

    - name: Upload RPM to Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/RPM/*.rpm
      if: steps.download.outputs.found
