name: Build_and_Release_Packages

on:
  release:
    types: [published]
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: './requirements.txt'

    - name: Build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cx_Freeze 
        pip install -r requirements.txt

    - name: Build packages
      run: |
        touch variables.env
        ls .
        python setup.py bdist_appimage

    - name: Validate directory contents
      run: ls .

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./artifacts
        overwrite: true

    - name: Upload MSI to Release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/*.msi


    - name: Upload APP to Release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/*.app


    - name: Upload DEB to Release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/*.deb


    - name: Upload RPM to Release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/*.rpm

