name: Build_and_Release_Packages

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-appimage:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: './requirements.txt'

    - name: Build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cx_Freeze 
        pip install -r requirements.txt

    - name: Build packages
      run: |
        touch variables.env
        ls .
        python setup.py bdist_appimage

    - name: Validate directory contents
      run: ls .

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: dist/*
        name: WoL.app
        overwrite: true

  release-appimage:
    needs: build-appimage
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./artifacts

    - name: Upload APP to Release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/*.app

  build-msi:
    runs-on: windows-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: './requirements.txt'

      - name: Build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cx_Freeze 
          pip install -r requirements.txt

      - name: Build packages
        run: |
          touch variables.env
          ls .
          python setup.py bdist_msi

      - name: Validate directory contents
        run: ls .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: dist/*
          name: WoL.msi
          overwrite: true

