name: AutoLint

on:
    push:
      branches: [ "main","develop" ]
    pull_request:
      branches: [ "main","develop" ]
    workflow_dispatch:
      

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        check-latest: true
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --disable=E0401 --output=lint.txt || true

    - name: CAT output
      run: cat lint.txt

    - name: Extract pylint score
      id: get_score
      run: |
        score=$(grep -oP 'rated at \K[0-9]+\.[0-9]+' lint.txt)
        echo "Pylint score is $score"
        echo "name=score::$score" >> $GITHUB_OUTPUT

    - name: Check pylint score
      run: |
        threshold=8.0  # Set your desired threshold here
        score=${{ steps.get_score.outputs.score }}
        if (( $(echo "$score < $threshold" | bc -l) )); then
          echo "Pylint score ($score) is below threshold ($threshold)."
          exit 1
        fi

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lint.txt
        path: lint.txt